stages:
    - build

workflow:
    rules:
        - if: '$CI_COMMIT_BRANCH'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

build:
    image: node:18
    tags:
        - docker
    variables:
        SPLUNK_HOME: '/tmp' # I only set this so that yarn run link:app creates a stage dir without error
        NODE_OPTIONS: '--openssl-legacy-provider' # UI toolkit depends on legacy SSL
    stage: build
    script:
        - mkdir /tmp/etc
        - mkdir /tmp/etc/apps
        - cd /tmp
        - git clone https://code.hurricanelabs.net/dev/broken_hosts_splunk_ui_toolkit.git --branch=main
        - cd broken_hosts_splunk_ui_toolkit
        - yarn run setup
        - cd packages/broken-hosts
        # - yarn run link:app
        # - ln -s $SPLUNK_HOME/etc/apps/broken_hosts $PWD/stage
        # The apps are different names so we need to hardcode this - as of now UI Toolkit does not allow dashes
        - ln -s $SPLUNK_HOME/etc/apps/broken_hosts /tmp/broken_hosts_splunk_ui_toolkit/packages/broken-hosts/stage
        - cd stage
        # - cp -r appserver $CI_PROJECT_DIR
        # - cp default/data/ui/views/*.xml $CI_PROJECT_DIR/default/data/ui/views
        # - curl --request POST --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" --url "https://code.hurricanelabs.net/api/v4/projects/234/repository/branches?branch=toolkit_v_$CI_JOB_ID&ref=toolkit"
        # - cd $CI_PROJECT_DIR
        - >
            git config --global user.email "ian@hurricanelabs.com" &&
            git config --global user.name "Ian" &&
            git checkout -b toolkit &&
            git add -f ./appserver ./default/data && git commit ./appserver ./default/data -m "Auto-build commit" &&
            git push -u https://a:$GITLAB_ACCESS_TOKEN@code.hurricanelabs.net/splunk/broken_hosts.git toolkit --force
        # - tar -v --transform "s,^\.,${CI_PROJECT_NAME}," --exclude="pylintrc" --exclude='.[^/]*' -czvf ${CI_PROJECT_NAME}.spl ./*
    artifacts:
        paths:
            - ${CI_PROJECT_NAME}.spl
    # only:
    #     refs:
    #         - merge_requests
    #     variables:
    #         - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
